### ISSUE TITLE
Problem with ZED and YOLO3 on Jetson TX2

### ISSUE THREAD

**Issue by alessand01** [pjreddie/darknet#949]
Hi,
I'm having some problems in processing a stream from a ZED camera with yolo3 (darknet) on a TX2.
I have done lots of tests and at the moment I'am trying to detect objects in an image loaded from the filesystem: the network can't find any objects if the ZED is opened (no need to call the grab function to produce this malfunctioning). Everything works well if I do not open the ZED.

Loading yolo3-tiny everything works well also with the ZED 'open'.

Any suggestion?
Thanks!

**Comment by alessand01** [comment]
Hi,
I have rebuilt darknet without CUDNN (using GPU, OPENCV and OPENMP) and now it works. Is it possible that the use of CUDNN causes problems with ZED SDK? 

The stereolabs support said that could be necessary to share with the ZED SDK the CUDA context of the application. Is it possible?

Thanks!

**Comment by erwincoumans** [comment]
I can into the same issue, running yolo v3 on TX2 hangs with ZED camera (not with ASUS Xtion).

What FPS do you get without CUDNN? Have you tried a different camera? With Xtion you can get around 15 to 17 FPS.

**Comment by nesnes** [comment]
If it's a CUDA context issue, using the same context in yolo and the ZED SDK should solve the issue.
I'm don't know about yolo, but the ZED SDK offers the two possibilities:
- Let the SDK create the context, and get it to initialise another lib: [getCUDAContext](https://www.stereolabs.com/developers/documentation/API/v2.5.1/classsl_1_1Camera.html#a77cf61f5049f2202d2101c304a81d554)
- Initialize the SDK with an existing context: [InitParameters.sdk_cuda_ctx](https://www.stereolabs.com/developers/documentation/API/v2.5.1/structsl_1_1InitParameters.html#ae684a455a5dc2e48a82b9aadc8c3ba53)

Someone had a similar issue in python, and his solution was to swap the current context depending on the function to call: [here](https://github.com/stereolabs/zed-python/issues/35#issuecomment-401622830)

**Comment by adujardin** [comment]
Hi,
I found a similar issue (even on desktop), the program was running but no objects were found if I opened the ZED, and working fine otherwise. A solution that seems to work is to call `cuda_set_device(0/*gpu_index*/);` after the ZED is opened.
Like :
1. Open the ZED
2. Call `cuda_set_device`
3. Init and run the network

It may indeed be a context issue, but I still don't know exactly what's happening. 

However, the difference between yolov3-tiny and regular yolov3 might come from the memory, it may be too much for the TX2.

**Comment by yuye1992** [comment]
Hi, 
I want to use yolo3 on tx2, but when I load the yolo3 model, the program was killed when it is only loaded to the 102 layer. Is it insufficient memory?

**Comment by shuxiao9058** [comment]
> Hi,
> I want to use yolo3 on tx2, but when I load the yolo3 model, the program was killed when it is only loaded to the 102 layer. Is it insufficient memory?

Do you fixed the error?

**Comment by adujardin** [comment]
@yuye1992 @shuxiao9058 For the memory usage issue, you should make sure that the config file is correct, specifically in yolo3.cfg :

https://github.com/pjreddie/darknet/blob/f86901f6177dfc6116360a13cc06ab680e0c86b0/cfg/yolov3.cfg#L2-L7

It should be 
```
# Testing
batch=1
subdivisions=1
# Training
#batch=64
#subdivisions=16
```
